[general]
import = [
	"~/.config/alacritty/theme.toml",
	"~/.config/alacritty/opacity.toml"
]

[window]
padding={x = 15}

[font]
size = 15
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Regular" }
italic = { family = "IosevkaTerm Nerd Font Mono", style = "Italic" }
bold = { family = "IosevkaTerm Nerd Font Mono", style = "Bold" }
bold_italic = { family = "IosevkaTerm Nerd Font Mono", style = "Italic Bold" }
# normal = { family = "Terminess Nerd Font Mono", style = "Regular" }
# italic = { family = "Terminess Nerd Font Mono", style = "Italic" }
# bold = { family = "Terminess Nerd Font Mono", style = "Bold" }
# bold_italic = { family = "Terminess Nerd Font Mono", style = "Italic Bold" }
