git:
  autoFetch: false
os:
  edit: "echo {{filename}} > /tmp/bceae2a5-1a92-4c7e-82be-5a489bf4a96c; kill -TERM $(pidof lazygit)"
  editAtLine: "echo {{filename}}:{{line}} > /tmp/bceae2a5-1a92-4c7e-82be-5a489bf4a96c; kill -TERM $(pidof lazygit)"
